function savestructOut = CD_save_data(filepath, source, datafile, inputfile, deletecurrent)
%SAVE_DATA Saves the data generated by 'TS_compute' into a file.
%   It must be run within a folder containing:
%       - A file of hctsa data (default: hctsa.mat)
%       - A file containing the required metadata
%       (default: inputs.mat)
%
%   'filepath' is the location in which the data will be saved (including
%   the file name and extension!). If no such file is present, one will be created
%
%   'source' is a string containing the function, original location or the
%   method used to collect the time series
%
%   (optional) 'datafile' is a string naming the file containing hctsa data (default:
%   HCTSA.mat)
%
%   (optional) 'inputfile' is a string naming the file containing parameter data (default:
%   inputs.mat)
%
%   (optional) 'deletecurrent' is a logical specifying whether the
%   existing data file is to be deleted (default: false)

%% Checking inputs
    
    if nargin < 2 || isempty(source)
        source = 'Unknown';
    end
    if nargin < 3 || isempty(datafile)
        datafile = 'HCTSA.mat';
    end
    if nargin < 4 || isempty(inputfile)
        inputfile = 'inputs.mat';
    end
    if nargin < 5 || isempty(deletecurrent)
        deletecurrent = false;
    end


    %find_folder = which('save_data.m');
    %filepath = [find_folder(1:end-length('save_data.m')), filename];
%% Delete current file if requested
    if ~isempty(filepath)
        filepath = fullfile(filepath);
        if deletecurrent && exist(filepath, 'file')
            delete(filepath)
        end
    end

%% Check if the required files exist
    if ~exist(fullfile(cd(), datafile), 'file') || ~exist(fullfile(cd(), inputfile), 'file')
    	error('One or more of the required files is missing')
    end
    %[~, subfoldername] = fileparts(paths{pathind});
    %fprintf('------------------------Adding Folder %g: %s------------------------\n', pathind, subfoldername)

    p = load(fullfile(cd(), inputfile));
    vars = fieldnames(p);
    inputs = p.(vars{1});
    
    load(fullfile(cd(), datafile), 'TS_DataMat', 'TimeSeries', 'Operations'); % Need labels and keywords

    [~, opidxs] = sort(Operations.ID); % Sort Operations by ID
    Operations = Operations(opidxs, :);
    TS_DataMat = TS_DataMat(:, opidxs); % Sort datamat by moving columns
    [~, TSidxs] = sort(TimeSeries.ID);
    TS_DataMat = TS_DataMat(TSidxs, :); % Sort datamat by moving rows, in case distributed_hctsa reordered them;
        % TS_DataMat rows should remain in the order common to the density
        
    labels = TimeSeries.Name;    
    keywords = TimeSeries.Keywords;
    
    numSubj = size(TS_DataMat, 1)./length(unique(keywords));
        
    [TS_DataMat, labels, keywords] = averageTS_DataMat(TS_DataMat, labels, keywords);
    
    %savestructcell = cell(length(inputs.cellType), 1);
    savestruct = repmat(struct('TS_DataMat', TS_DataMat, 'Operations', Operations, ...
                'Correlation', [], 'Source', source, ...
                'Inputs', [], 'Date', date, 'Correlation_Type', [], 'Correlation_Range', [], 'p_value', [], 'numSubj', numSubj), length(inputs.cellTypeID), 1);
    
    for i = 1:length(inputs.cellType)
        temparameters = inputs;%renameStructField(inputs, 'subject', 'subject'); % This will have extra density data, will distribute later


        %fprintf('------------------------%g%% complete, %gs elapsed------------------------\n', round(100*(i-1)./length(parameters.subject)), round(toc))
        savestruct(i, 1).TS_DataMat = TS_DataMat;%(i:length(inputs.subject):end, :);%(1+length(inputs.density)*(i-1):length(inputs.density)*i, :);
        temparameters.cellTypeID = inputs.cellTypeID(i);
        temparameters.cellType = inputs.cellType{i};
        temparameters.density = inputs.density{i};

        savestruct(i, 1).Inputs = temparameters;
        %savestructcell{i} = savestruct;
    end
    
    if ~isempty(filepath) && ~exist(filepath, 'file')
        time_series_data = struct('TS_DataMat', {}, 'Operations', {},...
            'Correlation', {}, 'Source', {}, 'Inputs', {}, 'Date', {},...
            'Correlation_Type', {}, 'Correlation_Range', {}, 'p_value', {}, 'numSubj', {});
        nrows = 0;
        save(filepath, 'time_series_data', 'nrows', '-v7.3')
    end
    %savestructcell = savestructcell(cellfun(@(x) ~isempty(x), savestructcell));
    %savestruct = cell2mat(savestructcell);
    if ~isempty(filepath)
        m = load(filepath);
        oldnrows = m.nrows;
        nrows = oldnrows + size(savestruct, 1);

        if isempty(m.time_series_data)
            m.time_series_data = savestruct;
        else
            m.time_series_data(oldnrows+1:nrows, 1) = savestruct; % Need faster way to modify time_series_data
        end
        m.nrows = nrows;
        fprintf('------------------------Finished Loading, Saving Results------------------------\n')
        save(filepath, '-struct', 'm', '-v7.3')%, '-nocompression')
        if nargout ~= 0
            savestructOut = savestruct; % So the ans doesn't clutter
        end
    end
    %fprintf('------------------------100%% complete, %gs elapsed------------------------\n', round(toc))
end
