old16Names = {...
    'DN_HistogramMode_10', ...
'AC_9', ...
'first_min_acf', ...
'SY_StdNthDer_1', ...
'CO_trev_1_num', ...
'CO_Embed2_Basic_tau_incircle_1', ...
'CO_Embed2_Basic_tau_incircle_2', ...
'SY_SpreadRandomLocal_ac2_100_meantaul', ...
'SY_SpreadRandomLocal_50_100_meantaul', ...
'PH_Walker_prop_01_sw_propcross', ...
'EN_SampEn_5_03_sampen1', ...
'FC_LocalSimple_mean1_taures', ...
'FC_LocalSimple_lfittau_taures', ...
'DN_OutlierInclude_abs_001_mdrmd', ...
'SB_MotifTwo_mean_hhh', ...
'SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1', ...
};

catch22Names = { ...
    'DN_HistogramMode_5', ...
'DN_HistogramMode_10', ...
'first_1e_ac', ...
'first_min_acf', ...
'CO_HistogramAMI_even_2_5', ...
'CO_trev_1_num', ...
'MD_hrv_classic_pnn40', ... 
'SB_BinaryStats_mean_longstretch1', ... 
'SB_TransitionMatrix_3ac_sumdiagcov', ... 
'PD_PeriodicityWang_th0.01', ...
'CO_Embed2_Dist_tau_d_expfit_meandiff', ...
'IN_AutoMutualInfoStats_40_gaussian_fmmi', ... 
'FC_LocalSimple_mean1_tauresrat', ...
'DN_OutlierInclude_p_001_mdrmd', ...
'DN_OutlierInclude_n_001_mdrmd', ...
'SP_Summaries_welch_rect_area_5_1', ... 
'SB_BinaryStats_diff_longstretch0', ...
'SB_MotifThree_quantile_hh', ...
'SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1', ...
'SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1', ...
'SP_Summaries_welch_rect_centroid', ...
'FC_LocalSimple_mean3_stderr'};

opIDs = [Operations.ID];
opNames = {Operations.Name};

opIDsOld16 = opIDs(cellfun(@(x) ismember(x, old16Names), opNames))
opIDsNew22 = opIDs(cellfun(@(x) ismember(x, catch22Names), opNames))