opNames = {Operations.Name};
opCSs = {Operations.CodeString};

sarab18names = {'CO_Embed2_Basic_tau.incircle_1', ...
                'CO_Embed2_Basic_tau.incircle_2', ...
                'FC_LocalSimple_mean1.taures', ...
                'SY_SpreadRandomLocal_ac2_100.meantaul', ...
                'DN_HistogramMode_10', ...
                'SY_StdNthDer_1', ...
                'AC_9', ...
                'SB_MotifTwo_mean.hhh', ...
                'EN_SampEn_5_03.sampen1', ...
                'CO_FirstMin_ac', ... 'first_min_acf' replaced
                'DN_OutlierInclude_abs_001.mdrmd', ...
                'CO_trev_1.num', ...
                'FC_LocalSimple_lfittau.taures', ...
                'SY_SpreadRandomLocal_50_100.meantaul', ...
                'SC_FluctAnal_2_rsrangefit_50_1_logi.prop_r1', ...
                'PH_ForcePotential_sine_1_1_1.proppos', ...
                'SP_Summaries_pgram_hamm.maxw', ...
                'SP_Summaries_welch_rect.maxw'};
            
% sum(contains(opNames, sarab18names))
length(opCSs(ismember(opCSs, sarab18names)))